PersonalWebsite.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.Core.Services.Interfaces;
using PersonalWebsite.DataLayer.Entities.Weblog;

namespace PersonalWebsite.Web.Controllers
{
    public class BlogController : Controller
    {
        private IBlogService _blogService;
        public BlogController(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public IActionResult Index(int pageId = 1, string search = "")
        {
            ViewBag.pageId = pageId;
            return View(_blogService.GetBlogList(pageId, 8, search));
        }

        [Route("ShowBlog/{id}")]
        public IActionResult ShowBlog(int id)
        {
            var blog = _blogService.GetBlogForShow(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        [HttpPost]
        public IActionResult CreateComment(Comment comment)
        {
            comment.IsDelete = false;
            comment.IsAdminRead = false;
            comment.CreateDate = DateTime.Now;

            _blogService.AddComment(comment);
            return View("ShowComment", _blogService.GetBlogComment(comment.BlogId));
        }

        public IActionResult ShowComment(int id, int pageId = 1)
        {
            return View(_blogService.GetBlogComment(id, pageId));
        }
    }
}

PersonalWebsite.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.Core.Services.Interfaces;

namespace PersonalWebsite.Web.Controllers
{
    public class ProjectController : Controller
    {
        private IUserService _userService;
        public ProjectController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index(int pageId = 1)
        {
            ViewBag.pageId = pageId;
            return View(_userService.GetProjectList(pageId, 16));
        }

        [Route("ShowProject/{id}")]
        public IActionResult ShowProject(int id)
        {
            var project = _userService.GetProjectById(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }
    }
}

PersonalWebsite.Web/Pages/Admin/Blogs/AddContent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonalWebsite.DataLayer.Entities.Weblog;
using PersonalWebsite.Core.Services.Interfaces;

namespace PersonalWebsite.Web.Pages.Admin.Blogs
{
    public class AddContentModel : PageModel
    {
        private IBlogService _blogService;
        public AddContentModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public void OnGet()
        {

        }

        public IActionResult OnPost(IFormFile imgContentUp)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _blogService.AddContent(Blog, imgContentUp);

            return RedirectToPage("Index");
        }
    }
}

PersonalWebsite.Web/Pages/Admin/Blogs/DeleteContent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonalWebsite.Core.DTOs.Blog;
using PersonalWebsite.Core.Services.Interfaces;
using PersonalWebsite.DataLayer.Entities.Weblog;

namespace PersonalWebsite.Web.Pages.Admin.Blogs
{
    public class DeleteContentModel : PageModel
    {
        private IBlogService _blogService;
        public DeleteContentModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public ShowBlogForAdminViewModel ShowBlogForAdminViewModel { get; set; }

        public void OnGet(int id)
        {
            ViewData["blogId"] = id;
            ShowBlogForAdminViewModel = _blogService.GetBlogInformation(id);
        }

        public IActionResult OnPost(int blogId)
        {
            _blogService.DeletContent(blogId);
            return RedirectToPage("Index");
        }
    }
}

PersonalWebsite.Web/Pages/Admin/Blogs/EditContent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonalWebsite.Core.Services.Interfaces;
using PersonalWebsite.DataLayer.Entities.Weblog;

namespace PersonalWebsite.Web.Pages.Admin.Blogs
{
    public class EditContentModel : PageModel
    {
        private IBlogService _blogService;
        public EditContentModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public void OnGet(int id)
        {
            Blog = _blogService.GetBlogById(id);
        }

        public IActionResult OnPost(Blog blog, IFormFile imgContentUp)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _blogService.UpdateBlog(blog, imgContentUp);

            return RedirectToPage("Index");
        }
    }
}

PersonalWebsite.Web/Pages/Admin/Blogs/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonalWebsite.Core.DTOs.Blog;
using PersonalWebsite.Core.Services.Interfaces;

namespace PersonalWebsite.Web.Pages.Admin.Blogs
{
    public class IndexModel : PageModel
    {
        private IBlogService _blogService;
        public IndexModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        //public List<ShowBlogForAdminViewModel> BlogList { get; set; }
        public SearchBlogForAdminViewModel SearchBlogForAdminViewModel { get; set; }

        public void OnGet(int pageId = 1, string filterTitle = "")
        {
            //BlogList = _blogService.GetBlogsForAdmin();
            SearchBlogForAdminViewModel = _blogService.GetFilteredBlog(pageId, filterTitle);
        }
    }
}

PersonalWebsite.Web/Views/Blog/Index.cshtml
@using PersonalWebsite.Core.Convertors
@model Tuple<List<PersonalWebsite.Core.DTOs.Blog.ShowBlogListItemViewModel>, int>

@{
    ViewData["Title"] = "بلاگ";
}

<section id="home-2" class="onepager_section_class first-onepage-section first-page-item">
</section>
<div style="background-image:url(/images/blog-top.jpg);" id="header" class="header-wrapper">
    <div class="center">
        <div class="logo">
            <a asp-controller="Blog" asp-action="Index" title="بلاگ"><img class="logoImage" src="/images/blog-logo-top.png" alt="نوشته های من" /><img class="logoImageRetina" src="images/logo.png" alt="عرفان فرهانیان" /></a>
            <div class="clear">
            </div>
        </div>
        <div dir="rtl" class="menu-wrapper">
            <div class="main-menu">
                <div class="menu-main-nav-menu-2-container">
                    <ul id="menu-main-nav-menu-2" class="sf-menu">
                        <li class="menu-item"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                        <li class="menu-item"><a asp-controller="Blog" asp-action="Index">بلاگ</a></li>
                        <li class="menu-item"><a asp-controller="Project" asp-action="Index">پروژه ها</a></li>
                    </ul>
                </div>
            </div>
            <div id="trigger-overlay" class="fa header-search fa-search">
            </div>
            <div class="menu-icons-inside">
                <div class="menu-icon menu-icon-mobile">
                    <span class="menu-icon-create"></span>
                </div>
            </div>
        </div>
        <div class="clear">
        </div>

        <div class="mobile-menu-wrapper">
            <div class="menu-main-nav-menu-container">
                <ul id="menu-main-nav-menu" class="mobile-menu">
                    <li class="menu-item"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                    <li class="menu-item"><a asp-controller="Blog" asp-action="Index">بلاگ</a></li>
                    <li class="menu-item"><a asp-controller="Project" asp-action="Index">پروژه ها</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="clear">
    </div>
</div>

<div class="container-wrapper home-container">
    <div id="container">
        <!-- start container -->
        <section id="single-port">
            <form action="/Blog" method="get">
                <input type="hidden" name="pageId" value="@ViewBag.PageId.ToString()" />
                <div class="center">
                    <div class="vc_row wpb_row vc_row-fluid">
                        <div class="wpb_column vc_column_container vc_col-sm-12">
                            <div class="vc_column-inner ">
                                <div class="wpb_wrapper">
                                    <div class="vc_hireme_posts_sh post-items-6925">
                                        <div class="posts-wrapper">
                                            <div class="top-page-link"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a> > <span>بلاگ</span></div>
                                            @foreach (var item in Model.Item1)
                                            {
                                                <div style="float:right; margin-top:20px;" class="post-article">
                                                    <a href="/ShowBlog/@item.BlogId" class="post-article-thumb">
                                                        <img style="width:370px; height:360px;" src="/blog/thumb/@item.BlogImageName" alt="@item.Title" />
                                                        <div class="clear"></div>
                                                        <div class="post-article-date-rotated-wrapper"><span class="post-article-date-rotated">@item.CreateDate.ToShamsi()</span></div>
                                                        <div class="view-overlay-bg"></div>
                                                        <ul class="post-article-overlay-details">
                                                            <li class="post-article-overlay-detail"><span class="post-article-overlay-detail-icon fa-eye"></span>287 مشاهده</li>
                                                            <li class="post-article-overlay-detail"><span class="post-article-overlay-detail-icon fa-comments-o"></span>0 نظر</li>
                                                        </ul>
                                                    </a>
                                                    <div class="clear"></div>
                                                    <div class="post-article-author">نوشته شده توسط  <a asp-controller="Blog" asp-action="Index" class="post-article-author-link">عرفان فرهانیان</a></div>
                                                    <div class="clear"></div><a href="/ShowBlog/@item.BlogId" class="post-article-title">@item.Title</a>
                                                    <div dir="rtl" class="post-article-excerpt">@item.SDescription</div>
                                                    <div class="clear"></div><a href="/ShowBlog/@item.BlogId" class="hireme_post_big_article_read_more">ادامه مطلب</a>
                                                </div>
                                            }
                                            <div class="clear"></div>
                                        </div>
                                        @if (Model.Item2 > 1)
                                        {
                                            <div class="pagination">
                                                @for (int i = 1; i <= Model.Item2; i++)
                                                {
                                                    <a href="/Blog?PageId=@i">@i</a>
                                                }
                                            </div>
                                        }
                                        <!-- /.pagination -->
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </form>

        </section>
    </div>
    <!-- end container -->
    <div class="clear"></div>
</div>

PersonalWebsite.Web/Views/Blog/ShowBlog.cshtml
@using PersonalWebsite.Core.Convertors
@model PersonalWebsite.DataLayer.Entities.Weblog.Blog

@{
    ViewData["Title"] = Model.Title;
}

<link rel='stylesheet' href='/css/bootstrap.css' type='text/css' media='all' />

<section id="home-2" class="onepager_section_class first-onepage-section first-page-item">
</section>
<div style="background-image:url(/images/blog-top.jpg);" id="header" class="header-wrapper">
    <div class="center">
        <div class="logo">
            <a href="index.html" title="بلاگ"><img class="logoImage" src="/images/blog-logo-top.png" alt="نوشته های من" /><img class="logoImageRetina" src="images/logo.png" alt="عرفان فرهانیان" /></a>
            <div class="clear">
            </div>
        </div>
        <div dir="rtl" class="menu-wrapper">
            <div class="main-menu">
                <div class="menu-main-nav-menu-2-container">
                    <ul id="menu-main-nav-menu-2" class="sf-menu">
                        <li class="menu-item"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                        <li class="menu-item"><a asp-controller="Blog" asp-action="Index">بلاگ</a></li>
                        <li class="menu-item"><a asp-controller="Project" asp-action="Index">پروژه ها</a></li>
                    </ul>
                </div>
            </div>
            <div id="trigger-overlay" class="fa header-search fa-search">
            </div>
            <div class="menu-icons-inside">
                <div class="menu-icon menu-icon-mobile">
                    <span class="menu-icon-create"></span>
                </div>
            </div>
        </div>
        <div class="clear">
        </div>

        <div class="mobile-menu-wrapper">
            <div class="menu-main-nav-menu-container">
                <ul id="menu-main-nav-menu" class="mobile-menu">
                    <li class="menu-item"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                    <li class="menu-item"><a asp-controller="Blog" asp-action="Index">بلاگ</a></li>
                    <li class="menu-item"><a asp-controller="Project" asp-action="Index">پروژه ها</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="clear">
    </div>
</div>

<div class="container-wrapper home-container">
    <div id="container">
        <!-- start container -->
        <section dir="rtl" id="single-port">
            <div class="top-page-link"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a> > <a asp-controller="Blog" asp-action="Index">بلاگ</a> > <span>@Model.Title</span></div>
            <br />
            <h2>@Model.Title</h2>
            <h6>نوشته شده در تاریخ <span>@Model.CreateDate.ToShamsi()</span></h6>

            <img style="height: 550px;" src="/blog/image/@Model.BlogImageName" alt="@Model.Title">
            <h3 style="line-height:35px;">"@Model.SDescription"</h3>
            <br />
            <figure>
                <p>@Html.Raw(Model.LDescription)</p>
            </figure>
            <div class="comment-form-wrapper">
                <br />
                <hr />
                <h2>ثبت نظر</h2>
                <form asp-controller="Blog" asp-action="CreateComment"
                      data-ajax="true"
                      data-ajax-method="post"
                      data-ajax-mode="replace"
                      data-ajaxt-update="#singlecomments"
                      data-ajax-success="Success">
                    <input type="hidden" name="comment.BlogId" value="@Model.BlogId" />
                    <div class="name-field">
                        <input class="form-control" type="text" id="comment_UserName" name="comment.UserName" required oninvalid="this.setCustomValidity('لطفا نام خود را وارد کنید')" oninput="this.setCustomValidity('')" placeholder="*نام" />
                    </div>
                    <br />
                    <div class="message-field">
                        <textarea class="form-control" name="comment.UserComment" id="comment_UserComment" rows="5" cols="100" required oninvalid="this.setCustomValidity('لطفا نظر خود را وارد کنید')" oninput="this.setCustomValidity('')" placeholder="*متن نظر"></textarea>
                    </div>
                    <br />
                    <input type="submit" value="ثبت" name="submit" class="btn btn-submit" />
                </form>

                <div dir="rtl" id="comments">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="page-header">
                                <h1><small class="pull-right"></small> نظرات </h1>
                            </div>
                            <div id="singlecomments" class="comments-list">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /.comment-form-wrapper -->
        <!-- /#comments -->
        <!-- /#comments -->
    </div>

    <!-- end container -->
    <div class="clear"></div>
</div>

@section Scripts
    {
    <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        function Success() {
            $("#comment_UserComment").val("");
            $("#comment_UserName").val("");
            alert("نظر شما پس از تایید در سایت قرار خواهد گرفت.")
        }

        $(function() {
            $("#singlecomments").load("/Blog/ShowComment/" + @Model.BlogId);
        });

        function pageComment(pageid) {
            $("#singlecomments").load("/Blog/ShowComment/" + @Model.BlogId+"?pageId=" + pageid);
        }
    </script>

}

PersonalWebsite.Web/Views/Blog/ShowComment.cshtml
@using PersonalWebsite.Core.Convertors
@model Tuple<List<PersonalWebsite.DataLayer.Entities.Weblog.Comment>, int>

@{
    Layout = null;
}


@foreach (var item in Model.Item1)
{
    <!------ Include the above in your HEAD tag ---------->
    <div class="media">
        <p class="pull-right"><small>در تاریخ : @item.CreateDate.ToShamsi()</small></p>
        <a class="media-left" href="#">
        </a>
        <div class="media-body">

            <h4 class="media-heading user_name">@item.UserName</h4>
            @item.UserComment

            <p><small><a href="#">لایک</a> - <a href="#">اشتراک گذاری</a></small></p>
        </div>
    </div>
}

<div class="pagination">

    @for (int i = 1; i <= Model.Item2; i++)
    {
        <a onclick="pageComment(@i)">@i</a>
    }

</div>